<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
	<IsTestProject>true</IsTestProject>
	<NoWarn>$(NoWarn);CA1707</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FsCheck.Xunit.v3" Version="3.3.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CedarRecon.Classification\CedarRecon.Classification.csproj" />
    <ProjectReference Include="..\..\src\CedarRecon.Core\CedarRecon.Core.csproj" />
    <ProjectReference Include="..\..\src\CedarRecon.Execution\CedarRecon.Execution.csproj" />
    <ProjectReference Include="..\..\src\CedarRecon.Infrastructure\CedarRecon.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\CedarRecon.Indexing\CedarRecon.Indexing.csproj" />
    <ProjectReference Include="..\CedarRecon.Reference\CedarRecon.Reference.csproj" />
  </ItemGroup>
	
  <ItemGroup>
    <None Include="Matching\Golden\*.json" CopyToOutputDirectory="PreserveNewest" />
	<None Include="Classification\Golden\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>